application: myflaskonappengineapp
version: 1
runtime: python27
threadsafe: yes
api_version: 1

default_expiration: "5d"

builtins:
- appstats: on
- deferred: on
- remote_api: on

# Use Third-party libraries <https://developers.google.com/appengine/docs/python/tools/libraries27>
libraries:
- name: jinja2
  version: "2.6"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /static
  static_dir: application/static

# gae_mini_profiler <https://github.com/kamens/gae_mini_profiler>
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: .*
  script: main.app
